"use client";
import { useState, type ReactNode } from "react";
import { api } from "@/lib/api";
import { useApi } from "@/hooks/use-api";
import { ErrorState, LoadingState, PageHeader, StatusBadge } from "@/components/ui";
import { formatBrokerMode, formatConnection } from "@/lib/display";
import { SystemTabs } from "@/components/section-tabs";

const environmentLabel=(value:string)=>value.toLowerCase()==="development"?"Development":value;
export default function SettingsPage(){const settings=useApi(api.settings);const caps=useApi(api.capabilities);const [showVersions,setShowVersions]=useState(false);if(settings.loading||caps.loading)return <><SystemTabs/><LoadingState/></>;if(!settings.data||!caps.data)return <><SystemTabs/><ErrorState message={settings.error||caps.error||"설정 조회 실패"} retry={()=>{void settings.refresh();void caps.refresh()}}/></>;const s=settings.data,c=caps.data;const versions=[["Scanner",s.scanner_version],["Research Prompt",s.research_prompt_version],["Research Schema",s.research_schema_version],["Evidence",s.evidence_version],["Risk",s.risk_version],["Execution",s.execution_version],["Strategy",s.strategy_version],["Shadow",s.shadow_variant_version],["Runtime Safety",s.operations_version]];const kiwoomConnected=c.market_data.kiwoom||c.broker.paper||c.broker.live;const marketData=c.market_data.fake||c.market_data.replay?"테스트 데이터":c.market_data.kiwoom?"실시간 데이터":"사용 불가";return <><SystemTabs/><PageHeader title="설정"/>
<div className="grid gap-6 xl:grid-cols-2"><section className="panel p-5"><h2 className="mb-2 font-semibold">연결 상태</h2><dl className="divide-y divide-line"><SettingRow label="키움증권"><StatusBadge value={kiwoomConnected?"CONNECTED":"NOT CONNECTED"} label={formatConnection(kiwoomConnected?"CONNECTED":"NOT CONNECTED")}/></SettingRow><SettingRow label="시장 데이터" value={marketData}/><SettingRow label="매매 모드" value={formatBrokerMode(s.broker_mode)}/></dl></section>
<section className="panel p-5"><h2 className="mb-2 font-semibold">시스템 정보</h2><dl className="divide-y divide-line"><SettingRow label="환경" value={environmentLabel(s.app_environment)}/><SettingRow label="버전" value="USB Internal V1"/></dl><button className="btn-muted mt-4" aria-expanded={showVersions} onClick={()=>setShowVersions(v=>!v)}>{showVersions?"상세 버전 닫기":"상세 버전 보기"}</button>{showVersions&&<dl className="mt-4 divide-y divide-line border-t border-line">{versions.map(([k,v])=><SettingRow key={k} label={k} value={v} mono/>)}</dl>}</section></div></>}

function SettingRow({label,value,mono=false,children}:{label:string;value?:string;mono?:boolean;children?:ReactNode}){return <div className="flex items-center justify-between gap-4 py-3 text-sm"><dt className="text-muted">{label}</dt><dd className={mono?"font-mono text-foreground":"text-foreground"}>{children??value}</dd></div>}
