"use client";
import { api } from "@/lib/api";
import { useApi } from "@/hooks/use-api";
import { ErrorState, LoadingState, PageHeader, StatusBadge } from "@/components/ui";
import { formatBrokerMode, formatCapability, formatConnection } from "@/lib/display";
import { SystemTabs } from "@/components/section-tabs";

const capabilityNames:Record<string,string>={fake:"Fake 데이터",replay:"Replay 데이터",kiwoom:"키움 실시간 데이터",simulation:"Simulation",paper:"Paper",live:"Live",scanner:"Scanner",research:"GPT 분석",shadow:"Shadow",runtime_safety:"Runtime Safety"};
export default function SettingsPage(){const settings=useApi(api.settings);const caps=useApi(api.capabilities);if(settings.loading||caps.loading)return <><SystemTabs/><LoadingState/></>;if(!settings.data||!caps.data)return <><SystemTabs/><ErrorState message={settings.error||caps.error||"설정 조회 실패"} retry={()=>{void settings.refresh();void caps.refresh()}}/></>;const s=settings.data,c=caps.data;const versions=[["Scanner",s.scanner_version],["GPT 분석 프롬프트",s.research_prompt_version],["GPT 분석 스키마",s.research_schema_version],["근거 점수",s.evidence_version],["Risk",s.risk_version],["Execution",s.execution_version],["Strategy",s.strategy_version],["Shadow Variant",s.shadow_variant_version],["Runtime Safety",s.operations_version]];return <><SystemTabs/><PageHeader title="설정" description="현재 시스템 환경, 버전, 지원 기능과 연결 상태를 확인합니다." actions={<><StatusBadge value={s.app_environment.toUpperCase()}/><StatusBadge value={s.broker_mode} label={formatBrokerMode(s.broker_mode)}/></>}/><div className="grid gap-6 xl:grid-cols-2"><section className="panel p-5"><h2 className="mb-4 font-semibold">시스템 버전</h2><dl className="divide-y divide-line">{versions.map(([k,v])=><div className="flex justify-between py-3 text-sm" key={k}><dt className="text-muted">{k}</dt><dd className="font-mono text-slate-200">{v}</dd></div>)}</dl></section><section className="space-y-6"><div className="panel p-5"><h2 className="mb-4 font-semibold">지원 기능</h2><Capability title="시장 데이터" values={c.market_data}/><Capability title="브로커" values={c.broker}/><Capability title="주요 기능" values={c.features}/></div><div className="panel border-slate-700 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">키움증권</h2><p className="mt-1 text-sm text-muted">아직 키움증권이 연결되지 않았습니다. 다음 단계에서 모의투자 API 연결을 진행합니다.</p></div><StatusBadge value="NOT CONNECTED" label={formatConnection("NOT CONNECTED")}/></div><p className="mt-4 text-xs text-muted">현재 연결 설정은 제공되지 않습니다.</p></div><div className="rounded-xl border border-red-900/70 bg-red-950/20 p-5"><h2 className="font-semibold text-red-200">보안 안내</h2><p className="mt-2 text-sm text-red-100/70">현재 USB에는 애플리케이션 로그인 기능이 없습니다. 외부 인터넷에 직접 공개하지 말고 방화벽, 사설망 또는 Reverse Proxy 인증을 통해 접근을 제한해야 합니다.</p></div></section></div></>}
function Capability({title,values}:{title:string;values:Record<string,boolean>}){return <div className="mb-5 last:mb-0"><p className="label mb-2">{title}</p><div className="flex flex-wrap gap-2">{Object.entries(values).map(([key,on])=><span key={key} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${on?"border-emerald-700 bg-emerald-950/40 text-emerald-300":"border-slate-700 bg-slate-900 text-slate-500"}`}>{capabilityNames[key]||key} · {formatCapability(on)}</span>)}</div></div>}
