export type RuntimeMode = "NORMAL" | "SAFE_MODE" | "HALTED";
export type Decision = "APPROVE" | "REJECT";
export type DecimalString = string;

export interface Failure { id: number; code: string; severity: "WARNING" | "ERROR" | "CRITICAL"; component: string; message: string; occurred_at: string; resolved: boolean; resolved_at: string | null }
export interface RuntimeStatus { mode: RuntimeMode; healthy: boolean; last_heartbeat: string | null; last_market_data: string | null; last_execution: string | null; last_reconciliation: string | null; unresolved_failure_count: number; last_failure: Failure | null; open_positions_count: number; open_orders_count: number }
export interface Dashboard { system_time: string; market: { trading_date: string; session: "PREMARKET" | "REGULAR" | "POSTMARKET" | "CLOSED"; is_trading_day: boolean; market_open: string | null; market_close: string | null }; runtime: { mode: RuntimeMode; healthy: boolean; last_heartbeat_at: string | null; unresolved_failure_count: number; last_failure: Failure | null }; scanner: { latest_run_id: number | null; trading_date: string | null; completed_at: string | null; candidate_count: number; top8_count: number }; research: { latest_analysis_id: number | null; analysis_at: string | null; approved_count: number }; trading: { broker_mode: string; open_positions_count: number; open_orders_count: number; paper_started_at: string | null }; shadow: { recent_result_count: number } }
export interface ScannerRun { id: number; trading_date: string; started_at: string; completed_at: string | null; status: string; provider: string; score_version: string; universe_count: number; excluded_count: number; candidate_count: number; top8_count: number }
export interface Candidate { candidate_id: number; rank: number | null; symbol: string; company_name: string | null; exchange: string | null; industry: string | null; quant_score: number | null; latest_close: number | null; latest_volume: number | null; market_cap: number | null; previous_open: number | null; previous_high: number | null; previous_low: number | null; previous_return_pct: number | null; raw_metrics: Record<string, number>; normalized_metrics: Record<string, number>; contributions: Record<string, number>; is_top8: boolean }
export interface ScannerSnapshot { run: ScannerRun; candidate_pool_count: number; candidates: Candidate[]; top8: Candidate[] }
export interface HumanDecision { symbol: string; decision: Decision; note: string | null; decided_at: string }
export interface ExtendedMarketQuote { price: number | null; return_pct: number | null; observed_at: string | null; reason: "NOT_FETCHED" | "NOT_AVAILABLE_FROM_PROVIDER" | "INSUFFICIENT_HISTORY" | "OUTSIDE_SESSION" | "PROVIDER_ERROR" | null }
export interface MarketSnapshot { company_name: string | null; exchange: string | null; industry: string | null; market_cap: number | null; previous_open: number | null; previous_high: number | null; previous_low: number | null; previous_close: number | null; previous_return_pct: number | null; previous_volume: number | null; rvol: number | null }
export interface ResearchCandidate { scanner_candidate_id: number; symbol: string; quant_rank: number | null; gpt_rank: number; quant_score: number | null; overall_score: number; catalyst_score: number; fundamental_score: number; momentum_score: number; risk_score: number; evidence_confidence: number; catalyst_duration: string; stop_profile: string; trailing_profile: string; overnight_suitability: string; company_summary: string; catalyst_summary: string; risk_summary: string; invalidation_summary: string; unknown_fields: string[]; human_decision: HumanDecision | null }
export interface ResearchAnalysis { analysis: { id: number; scanner_run_id: number; trading_date: string; analysis_at: string; imported_at: string; provider: string; model: string; prompt_version: string; schema_version: string; evidence_version: string; status: string }; candidates: ResearchCandidate[] }
export type AdoptionClassification = "ADOPTION_CANDIDATE" | "REVIEW_REQUIRED" | "EXCLUDED";
export interface AdoptionItem extends ResearchCandidate, MarketSnapshot { analysis_id: number; scanner_run_id: number; recommendation_rank: number; evidence_score: number; relative_strength: number | null; momentum: number | null; classification: AdoptionClassification; rank_delta: number | null; rank_delta_label: string; rank_direction: "UP" | "DOWN" | "UNCHANGED" | "NEUTRAL"; strengths: string[]; warnings: string[]; rank_explanation: string }
export interface AdoptionResponse { filter_version: "adoption_filter_v0"; analysis_id: number; scanner_run_id: number; trading_date: string; counts: { adoption_candidate: number; review_required: number; excluded: number }; items: AdoptionItem[] }
export interface Source { claim: string; title: string; url: string; source_type: string; domain: string; published_at: string | null }
export interface ResearchDetail extends ResearchCandidate, MarketSnapshot { sources: Source[]; premarket: ExtendedMarketQuote; postmarket: ExtendedMarketQuote; market_cap_reason: "UNIT_UNCONFIRMED"; industry_reason: "NOT_AVAILABLE_FROM_PROVIDER" }
export interface StrategyState { symbol: string; trading_date: string; book: string; variant: string; phase: string; phase_reason: string | null; entry_price: DecimalString | null; initial_stop: DecimalString | null; active_stop: DecimalString | null; highest_price: DecimalString | null; add_count: number; holding_day: number; overnight: boolean }
export interface TradingAccount { currency?: string | null; equity?: DecimalString | null; cash?: DecimalString | null; invested_notional?: DecimalString | null; unrealized_pnl?: DecimalString | null; realized_pnl?: DecimalString | null; today_pnl?: DecimalString | null }
export interface TradingPosition { symbol: string; currency?: string | null; invested_notional?: DecimalString | null; quantity?: DecimalString | null; average_price?: DecimalString | null; mark_price?: DecimalString | null; market_value?: DecimalString | null; unrealized_pnl?: DecimalString | null; return_pct?: DecimalString | null; active_stop?: DecimalString | null; phase?: string | null }
export interface TradingOverview { broker_mode: string; availability: string; account: TradingAccount | null; open_positions: TradingPosition[]; open_orders: unknown[]; strategy_states: StrategyState[] }
export interface DailyPerformance { trading_date: string; opening_equity: DecimalString; closing_equity: DecimalString; cash: DecimalString; position_market_value: DecimalString; daily_pnl: DecimalString; daily_return: DecimalString; cumulative_pnl: DecimalString }
export interface Order { order_id: string; broker_type: string; symbol: string; side: string; requested_quantity: DecimalString; filled_quantity: DecimalString; status: string; rejection_reason: string | null; reference_price: DecimalString; submitted_at: string; completed_at: string | null; execution_version: string }
export interface Fill { fill_id: string; order_id: string; symbol: string; fill_price: DecimalString; quantity: DecimalString; spread_cost: DecimalString; slippage_cost: DecimalString; commission: DecimalString; fx_cost: DecimalString; total_cost: DecimalString; filled_at: string }
export interface Trade { id: string; symbol: string; variant: string; control: boolean; status: string; entry: DecimalString | null; exit: DecimalString | null; gross_pnl: DecimalString; net_pnl: DecimalString; gross_r: DecimalString; net_r: DecimalString; total_cost: DecimalString; exit_reason: string | null; holding_duration: number; ambiguous_count: number; source: string }
export interface ShadowVariant { variant: string; control: boolean; candidate_paths: number; trades: number; no_trade: number; wins: number; losses: number; net_pnl: DecimalString; net_r: DecimalString; avg_net_r: DecimalString; total_cost: DecimalString; ambiguity: number; overnight: number; pyramid: number | null; source: string }
export interface ShadowSummary { source: string; variants: ShadowVariant[] }
export interface ReplayReport { available: boolean; generated_at: string | null; summary: Record<string, unknown>; variants: unknown[]; invariants: unknown; determinism: unknown }
export interface Settings { app_environment: string; scanner_version: string; research_prompt_version: string; research_schema_version: string; evidence_version: string; risk_version: string; execution_version: string; strategy_version: string; shadow_variant_version: string; operations_version: string; adoption_filter_version: string; broker_mode: string }
export interface Capabilities { market_data: { fake: boolean; replay: boolean; kiwoom: boolean }; broker: { simulation: boolean; paper: boolean; live: boolean }; features: { scanner: boolean; research: boolean; shadow: boolean; runtime_safety: boolean } }
