"use client";
import { useState } from "react";
import { api, ApiError } from "@/lib/api";
import { etTime } from "@/lib/format";
import { useApi } from "@/hooks/use-api";
import { useToast } from "@/components/toast";
import { EmptyState, ErrorState, LoadingState, MetricCard, Modal, PageHeader, StatusBadge } from "@/components/ui";
import type { ResearchDetail } from "@/types/api";
import { formatDecisionStatus } from "@/lib/display";
import { AnalysisTabs } from "@/components/section-tabs";

export default function ResearchPage() {
  const result=useApi(api.research); const toast=useToast(); const [raw,setRaw]=useState(""); const [busy,setBusy]=useState(false); const [detail,setDetail]=useState<ResearchDetail|null>(null); const [detailError,setDetailError]=useState<string|null>(null);
  async function importJson(){if(!raw.trim()){toast("GPT JSON을 입력하세요.",true);return}setBusy(true);try{const response=await api.importResearch(raw);toast(`${response.candidate_count}개 후보 분석을 불러왔습니다.`);setRaw("");await result.refresh()}catch(e){toast(e instanceof ApiError?e.message:"불러오기에 실패했습니다.",true)}finally{setBusy(false)}}
  async function openDetail(symbol:string){if(!result.data)return;setDetailError(null);try{setDetail(await api.researchDetail(result.data.analysis.id,symbol))}catch(e){setDetailError(e instanceof Error?e.message:"상세 조회 실패")}}
  async function decide(symbol:string,decision:"APPROVE"|"REJECT"){if(!result.data)return;if(decision==="REJECT"&&result.data.candidates.find(c=>c.symbol===symbol)?.human_decision?.decision==="APPROVE"&&!window.confirm("기존 APPROVE를 REJECT로 변경할까요?"))return;setBusy(true);try{await api.decide(result.data.analysis.id,symbol,decision);toast(`${symbol} 결정을 ${decision}로 변경했습니다.`);await result.refresh();if(detail?.symbol===symbol)setDetail(await api.researchDetail(result.data.analysis.id,symbol))}catch(e){toast(e instanceof ApiError&&e.status===409?"최대 2종목까지 승인할 수 있습니다.":e instanceof Error?e.message:"결정 저장 실패",true)}finally{setBusy(false)}}
  return <><AnalysisTabs/><PageHeader title="GPT 분석 및 투자 승인" description="ChatGPT 분석 결과를 불러와 후보 종목의 순위, 근거, 위험요인을 확인하고 최종 승인 여부를 결정합니다."/>
    <ol className="panel mb-5 grid gap-3 p-4 text-sm sm:grid-cols-4">{["1. 프롬프트 복사","2. ChatGPT 분석","3. 결과 붙여넣기","4. 승인 / 거절"].map(step=><li className="rounded-lg bg-slate-950/60 px-3 py-2 text-slate-300" key={step}>{step}</li>)}</ol>
    <section className="panel mb-7 p-5"><h2 className="font-semibold">GPT 분석 결과 불러오기</h2><p className="mb-3 mt-1 text-xs text-muted">후보 종목 화면에서 복사한 프롬프트를 ChatGPT에 입력하고, 반환된 JSON을 그대로 붙여넣으세요.</p><textarea className="input h-36 resize-y overflow-auto font-mono text-xs leading-5" value={raw} onChange={e=>setRaw(e.target.value)} placeholder="ChatGPT가 반환한 JSON을 여기에 붙여넣으세요."/><div className="mt-3 flex justify-end"><button className="btn-primary" disabled={busy||!raw.trim()} onClick={()=>void importJson()}>검증 후 불러오기</button></div></section>
    {result.loading?<LoadingState/>:result.error&&!result.data?<ErrorState message={result.error} retry={result.refresh}/>:result.data?<><section className="mb-5 grid gap-3 sm:grid-cols-3"><MetricCard label="분석 종목" value={result.data.candidates.length}/><MetricCard label="승인 현황" value={result.data.candidates.filter(c=>c.human_decision?.decision==="APPROVE").length}/><MetricCard label="분석 시각" value={etTime(result.data.analysis.analysis_at)} detail={`${result.data.analysis.provider} · ${result.data.analysis.model}`}/></section><div className="table-wrap"><table><thead><tr><th>GPT 순위</th><th>종목</th><th>Quant 순위</th><th>종합</th><th title="상승 촉매">Catalyst</th><th title="기업 / 실적">Fundamental</th><th title="가격 흐름">Momentum</th><th title="위험 요인">Risk</th><th><span title="출처 품질과 핵심 주장 근거 범위를 기반으로 계산된 점수입니다.">근거 점수 ⓘ</span></th><th>투자 결정</th><th>작업</th></tr></thead><tbody>{result.data.candidates.map(c=><tr key={c.symbol} className="cursor-pointer" onClick={()=>void openDetail(c.symbol)}><td className="font-bold text-cyan-300">#{c.gpt_rank}</td><td className="font-bold text-white">{c.symbol}</td><td>#{c.quant_rank}</td><td>{c.overall_score}</td><td>{c.catalyst_score}</td><td>{c.fundamental_score}</td><td>{c.momentum_score}</td><td>{c.risk_score}</td><td>{c.evidence_confidence}</td><td><StatusBadge value={c.human_decision?.decision||"UNDECIDED"} label={formatDecisionStatus(c.human_decision?.decision)}/></td><td onClick={e=>e.stopPropagation()}><div className="flex gap-1"><button className="btn-primary px-2 py-1 text-xs" disabled={busy} onClick={()=>void decide(c.symbol,"APPROVE")}>승인</button><button className="btn-muted px-2 py-1 text-xs" disabled={busy} onClick={()=>void decide(c.symbol,"REJECT")}>거절</button></div></td></tr>)}</tbody></table></div></>:<EmptyState title="아직 불러온 GPT 분석 결과가 없습니다." description="위 입력창에 ChatGPT 분석 JSON을 붙여넣으면 종목별 순위와 근거가 표시됩니다."/>}
    <Modal open={!!detail||!!detailError} title={`${detail?.symbol||"GPT 분석"} · 종목 분석`} onClose={()=>{setDetail(null);setDetailError(null)}}>{detailError?<p className="text-red-300">{detailError}</p>:detail&&<div className="space-y-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><MetricCard label="GPT 순위" value={`#${detail.gpt_rank}`}/><MetricCard label="Quant 순위" value={`#${detail.quant_rank}`}/><MetricCard label="근거 점수" value={detail.evidence_confidence}/><MetricCard label="투자 결정" value={<StatusBadge value={detail.human_decision?.decision||"UNDECIDED"} label={formatDecisionStatus(detail.human_decision?.decision)}/>}/></div>{[["회사",detail.company_summary],["Catalyst",detail.catalyst_summary],["위험요인",detail.risk_summary],["무효화 조건",detail.invalidation_summary]].map(([t,v])=><section key={t}><h3 className="label mb-1">{t}</h3><p className="text-sm leading-6 text-slate-300">{v}</p></section>)}<section><h3 className="label mb-2">분석 프로필</h3><div className="flex flex-wrap gap-2">{[detail.catalyst_duration,detail.stop_profile,detail.trailing_profile,detail.overnight_suitability].map(v=><StatusBadge key={v} value={v}/>)}</div></section>{detail.unknown_fields.length>0&&<section><h3 className="label mb-2">확인되지 않은 항목</h3><p className="text-sm text-amber-300">{detail.unknown_fields.join(", ")}</p></section>}<section><h3 className="label mb-2">출처</h3>{detail.sources.length?<div className="space-y-2">{detail.sources.map((s,i)=><a key={`${s.url}-${i}`} href={s.url} target="_blank" rel="noreferrer" className="block rounded-lg border border-line p-3 hover:border-cyan-700"><div className="flex items-center gap-2"><StatusBadge value={s.source_type}/><span className="text-xs text-muted">{s.domain}</span></div><p className="mt-2 text-sm font-medium">{s.title}</p><p className="mt-1 text-xs text-muted">{s.claim}</p></a>)}</div>:<p className="text-sm text-muted">등록된 출처가 없습니다.</p>}</section><div className="flex gap-2"><button className="btn-primary" onClick={()=>void decide(detail.symbol,"APPROVE")}>승인</button><button className="btn-muted" onClick={()=>void decide(detail.symbol,"REJECT")}>거절</button></div></div>}</Modal>
  </>;
}
