"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState, type ReactNode } from "react";
import { api } from "@/lib/api";
import { etTime } from "@/lib/format";
import { useApi } from "@/hooks/use-api";
import { RuntimeBanner, StatusBadge } from "@/components/ui";

const nav = [["/", "⌂", "대시보드"], ["/candidates", "◎", "후보 종목"], ["/research", "◇", "GPT 분석"], ["/trading", "↗", "매매 현황"], ["/shadow", "≋", "전략 검증"], ["/runtime", "⚠", "시스템 상태"], ["/settings", "⚙", "설정"]];
export function AppShell({ children }: { children: ReactNode }) { const path = usePathname(); const [open,setOpen] = useState(false); const state = useApi(api.dashboard, 20000); const runtime = state.data?.runtime.mode || "NORMAL"; return <div className="min-h-screen"><RuntimeBanner mode={runtime}/><aside className={`fixed inset-y-0 left-0 z-40 w-60 border-r border-line bg-[#0a1019] transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-16 items-center border-b border-line px-5"><span className="mr-2 h-2.5 w-2.5 rounded-full bg-cyan-400 shadow-[0_0_12px_#22d3ee]"/><span className="text-lg font-bold tracking-[0.2em]">USB</span></div><nav className="space-y-1 p-3">{nav.map(([href,icon,label]) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm ${path === href ? "bg-cyan-500/[0.07] font-semibold text-cyan-300" : "text-slate-400 hover:bg-slate-800/70 hover:text-white"}`}><span className="w-5 text-center">{icon}</span>{label}{label === "시스템 상태" && (state.data?.runtime.unresolved_failure_count || 0) > 0 && <span className="ml-auto rounded-full bg-red-500/20 px-2 text-xs text-red-300">{state.data?.runtime.unresolved_failure_count}</span>}</Link>)}</nav><div className="absolute bottom-0 w-full border-t border-line p-4 text-xs"><div className="mb-3 flex items-center justify-between"><span className="text-muted">Backend 연결</span><span className={state.error ? "text-red-400" : "text-emerald-400"}>● {state.error ? "연결 안 됨" : "연결됨"}</span></div><div className="flex items-center justify-between"><span className="text-muted">브로커</span><StatusBadge value={state.data?.trading.broker_mode || "UNKNOWN"}/></div></div></aside><div className="lg:pl-60"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-line bg-ink/90 px-4 backdrop-blur md:px-7"><div className="flex items-center gap-3"><button className="btn-muted lg:hidden" onClick={() => setOpen(!open)} aria-label="메뉴">☰</button><div><p className="label">미국주식 트레이딩 시스템</p><p className="text-sm font-medium">{state.data ? etTime(state.data.system_time) : "연결 중…"}</p></div></div><div className="hidden items-center gap-3 sm:flex"><span className="text-xs text-muted">시장</span><StatusBadge value={state.data?.market.session || "UNKNOWN"}/><span className="text-xs text-muted">시스템</span><StatusBadge value={runtime}/></div></header><main className="p-4 md:p-7 xl:p-9">{children}</main></div></div>; }
