"use client";
import { useState } from "react";
import { api, ApiError } from "@/lib/api";
import { etTime } from "@/lib/format";
import { useApi } from "@/hooks/use-api";
import { useToast } from "@/components/toast";
import { EmptyState, ErrorState, LoadingState, MetricCard, Modal, PageHeader, StatusBadge } from "@/components/ui";
import { formatFailureCodeDescription, formatResolved, formatRuntimeHealth, formatRuntimeMode, formatSeverity } from "@/lib/display";
import { SystemTabs } from "@/components/section-tabs";
type Action="safe-mode"|"halt"|"kill-switch"|null;
const recorded=(value:string|null,empty:string)=>value?etTime(value):empty;
export default function RuntimePage(){const runtime=useApi(api.runtime,10000);const failures=useApi(api.failures,10000);const toast=useToast();const [action,setAction]=useState<Action>(null);const [reason,setReason]=useState("");const [understood,setUnderstood]=useState(false);const [busy,setBusy]=useState(false);const [reconcile,setReconcile]=useState<{matched:boolean;mismatches:Array<{type:string;symbol:string;details:string}>}|null>(null);
async function runAction(){if(!action||!reason.trim())return;setBusy(true);try{if(action==="kill-switch")await api.killSwitch(reason);else await api.runtimeAction(action,reason);toast("운영 제어 요청이 완료되었습니다.");setAction(null);setReason("");setUnderstood(false);await runtime.refresh();await failures.refresh()}catch(e){toast(e instanceof Error?e.message:"운영 제어 실패",true)}finally{setBusy(false)}}
async function recover(){setBusy(true);try{await api.recover();toast("정상 모드로 복구했습니다.");await runtime.refresh()}catch(e){toast(e instanceof ApiError?e.message:"복구 조건을 충족하지 못했습니다.",true)}finally{setBusy(false)}}
async function doReconcile(){setBusy(true);try{const value=await api.reconcile();setReconcile(value);toast(value.matched?"상태 대조 PASS":"상태 불일치가 발견되었습니다.",!value.matched);await runtime.refresh();await failures.refresh()}catch(e){toast(e instanceof Error?e.message:"상태 대조 실패",true)}finally{setBusy(false)}}
async function resolve(id:number){setBusy(true);try{await api.resolveFailure(id);toast("장애 기록을 해결 상태로 변경했습니다.");await failures.refresh();await runtime.refresh()}catch(e){toast(e instanceof Error?e.message:"해결 처리 실패",true)}finally{setBusy(false)}}
if(runtime.loading)return <><SystemTabs/><LoadingState/></>;if(!runtime.data)return <><SystemTabs/><ErrorState message={runtime.error||"시스템 상태 조회 실패"} retry={runtime.refresh}/></>;const r=runtime.data;return <><SystemTabs/><PageHeader title="시스템 상태" description="시스템 상태와 장애를 확인하고 안전 모드, 중지, 복구 작업을 수행합니다." actions={<StatusBadge value={r.mode} label={formatRuntimeMode(r.mode)} showRaw/>} />
<section className="mb-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><MetricCard label="전체 상태" value={formatRuntimeHealth(r.healthy)} detail={r.healthy?"정상 운영 중":"확인 필요"} accent={!r.healthy?"warning":undefined}/><MetricCard label="Heartbeat" value={recorded(r.last_heartbeat,"미수신")}/><MetricCard label="시세 데이터" value={recorded(r.last_market_data,"미수신")}/><MetricCard label="주문 실행" value={recorded(r.last_execution,"미실행")}/><MetricCard label="상태 대조" value={recorded(r.last_reconciliation,"미실행")}/><MetricCard label="보유 포지션" value={r.open_positions_count}/><MetricCard label="미체결 주문" value={r.open_orders_count}/></section>
<section className="mb-8"><h2 className="font-semibold">장애 및 오류 기록</h2><p className="mb-3 mt-1 text-xs text-muted">운영 모드와 시스템 건강 상태는 별도로 표시됩니다. NORMAL 상태에서도 미해결 경고나 최근 장애가 있으면 전체 상태가 ‘확인 필요’로 표시될 수 있습니다.</p><p className="mb-3 mt-1 text-xs text-muted">해결 처리는 장애 기록의 상태만 변경합니다. 시스템을 정상 모드로 복구하려면 별도의 복구 절차가 필요합니다.</p>{failures.data?.length?<div className="table-wrap"><table><thead><tr><th>시각</th><th>심각도</th><th>코드</th><th>구성요소</th><th>메시지</th><th>해결 여부</th><th></th></tr></thead><tbody>{[...failures.data].sort((a,b)=>Number(a.resolved)-Number(b.resolved)).map(f=><tr key={f.id}><td>{etTime(f.occurred_at)}</td><td><StatusBadge value={f.severity} label={formatSeverity(f.severity)}/></td><td><span className="font-mono text-xs">{f.code}</span><small className="mt-1 block text-muted">{formatFailureCodeDescription(f.code)}</small></td><td>{f.component}</td><td className="max-w-md">{f.message}</td><td>{formatResolved(f.resolved)}</td><td>{!f.resolved&&<button className="btn-muted px-2 py-1 text-xs" disabled={busy} onClick={()=>void resolve(f.id)}>해결 처리</button>}</td></tr>)}</tbody></table></div>:<EmptyState title="현재 미해결 장애가 없습니다."/>}</section>
<section className="rounded-xl border border-red-900/70 bg-red-950/10 p-5"><h2 className="text-lg font-semibold">운영 제어</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Control title="안전 모드 전환" description="신규 진입 및 추가매수를 차단하고 기존 포지션의 위험 축소·청산은 허용합니다." buttonClass="btn-muted border-amber-700 text-amber-300" onClick={()=>setAction("safe-mode")}/><Control title="자동 매매 중지" description="자동 Strategy Action을 중단합니다." buttonClass="btn-danger" onClick={()=>setAction("halt")}/></div><div className="my-6 border-t border-line"/><h2 className="text-lg font-semibold">복구 및 검증</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Control title="상태 대조 실행" description="내부 상태와 Broker 상태가 일치하는지 확인합니다." disabled={busy} onClick={()=>void doReconcile()}/><Control title="정상 모드 복구" description="복구 조건을 확인한 뒤 NORMAL 상태로 복귀합니다." disabled={busy} onClick={()=>void recover()}/></div>{reconcile&&<div className={`mt-4 rounded-lg border p-4 ${reconcile.matched?"border-emerald-800 bg-emerald-950/30":"border-red-800 bg-red-950/30"}`}><p className="font-semibold">{reconcile.matched?"PASS":"MISMATCH"}</p>{reconcile.mismatches.map((m,i)=><p key={i} className="mt-2 text-sm text-muted">{m.type} · {m.symbol} · {m.details}</p>)}</div>}<div className="my-6 border-t border-red-900/60"/><h2 className="font-semibold text-red-300">비상 중지 (Kill Switch)</h2><p className="mt-1 text-sm text-muted">시스템을 HALTED 상태로 전환하고 연결된 Broker 포지션의 청산을 시도할 수 있습니다.</p><button className="btn-danger mt-3" onClick={()=>setAction("kill-switch")}>Kill Switch 열기</button></section>
<Modal open={!!action} title={action==="kill-switch"?"비상 중지 · 2단계 확인":action==="halt"?"자동 매매 중지":"안전 모드 전환"} onClose={()=>!busy&&setAction(null)}><p className="mb-4 text-sm text-slate-300">{action==="safe-mode"?"신규 진입 및 추가매수를 차단하며 기존 포지션의 위험 축소·청산은 허용됩니다.":action==="halt"?"자동 Strategy Action을 중단합니다.":"시스템을 HALTED 상태로 전환하고 현재 포지션의 청산을 시도할 수 있습니다."}</p><label className="label mb-2 block" htmlFor="reason">운영 사유</label><textarea id="reason" className="input min-h-24" value={reason} onChange={e=>setReason(e.target.value)} placeholder="사유를 입력하세요."/>{action==="kill-switch"&&<label className="mt-4 flex items-start gap-3 rounded-lg border border-red-900 p-3 text-sm text-red-200"><input type="checkbox" className="mt-1" checked={understood} onChange={e=>setUnderstood(e.target.checked)}/><span>현재 포지션 청산 시도가 발생할 수 있음을 이해했습니다.</span></label>}<div className="mt-5 flex justify-end gap-2"><button className="btn-muted" onClick={()=>setAction(null)}>취소</button><button className={action==="safe-mode"?"btn-primary":"btn-danger"} disabled={busy||!reason.trim()||(action==="kill-switch"&&!understood)} onClick={()=>void runAction()}>{action==="kill-switch"?"확인 후 Kill Switch 실행":action==="halt"?"HALTED 전환":"SAFE_MODE 전환"}</button></div></Modal></>}
function Control({title,description,onClick,buttonClass="btn-muted",disabled=false}:{title:string;description:string;onClick:()=>void;buttonClass?:string;disabled?:boolean}){return <div className="rounded-lg border border-line bg-slate-950/30 p-4"><button className={buttonClass} disabled={disabled} onClick={onClick}>{title}</button><p className="mt-3 text-xs leading-5 text-muted">{description}</p></div>}
