"use client";
import { useState } from "react";
import { api, ApiError } from "@/lib/api";
import { etTime } from "@/lib/format";
import { useApi } from "@/hooks/use-api";
import { useToast } from "@/components/toast";
import { EmptyState, ErrorState, LoadingState, Modal, PageHeader, StatusBadge } from "@/components/ui";
import { formatFailureCodeDescription, formatResolved, formatRuntimeHealth, formatRuntimeMode, formatSeverity } from "@/lib/display";
import { SystemTabs } from "@/components/section-tabs";
import type { RuntimeMode } from "@/types/api";

type Action="safe-mode"|"halt"|"kill-switch"|null;
const recorded=(value:string|null,empty:string)=>value?etTime(value):empty;
const modeStatus=(mode:RuntimeMode,healthy:boolean)=>mode==="SAFE_MODE"?{title:"안전 모드",detail:"신규 진입 차단 중"}:mode==="HALTED"?{title:"자동 매매 중지",detail:"자동 Strategy Action 중단"}:{title:formatRuntimeHealth(healthy),detail:healthy?"현재 미해결 장애 없음":"해결이 필요한 장애가 있습니다."};

export default function RuntimePage(){const runtime=useApi(api.runtime,10000);const failures=useApi(api.failures,10000);const toast=useToast();const [action,setAction]=useState<Action>(null);const [reason,setReason]=useState("");const [understood,setUnderstood]=useState(false);const [busy,setBusy]=useState(false);const [showAllFailures,setShowAllFailures]=useState(false);const [reconcile,setReconcile]=useState<{matched:boolean;mismatches:Array<{type:string;symbol:string;details:string}>}|null>(null);
async function runAction(){if(!action||!reason.trim())return;setBusy(true);try{if(action==="kill-switch")await api.killSwitch(reason);else await api.runtimeAction(action,reason);toast("운영 제어 요청이 완료되었습니다.");setAction(null);setReason("");setUnderstood(false);await runtime.refresh();await failures.refresh()}catch(e){toast(e instanceof Error?e.message:"운영 제어 실패",true)}finally{setBusy(false)}}
async function recover(){setBusy(true);try{await api.recover();toast("정상 모드로 복구했습니다.");await runtime.refresh()}catch(e){toast(e instanceof ApiError?e.message:"복구 조건을 충족하지 못했습니다.",true)}finally{setBusy(false)}}
async function doReconcile(){setBusy(true);try{const value=await api.reconcile();setReconcile(value);toast(value.matched?"상태 대조 PASS":"상태 불일치가 발견되었습니다.",!value.matched);await runtime.refresh();await failures.refresh()}catch(e){toast(e instanceof Error?e.message:"상태 대조 실패",true)}finally{setBusy(false)}}
async function resolve(id:number){setBusy(true);try{await api.resolveFailure(id);toast("장애 기록을 해결 상태로 변경했습니다.");await failures.refresh();await runtime.refresh()}catch(e){toast(e instanceof Error?e.message:"해결 처리 실패",true)}finally{setBusy(false)}}
if(runtime.loading)return <><SystemTabs/><LoadingState/></>;if(!runtime.data)return <><SystemTabs/><ErrorState message={runtime.error||"시스템 상태 조회 실패"} retry={runtime.refresh}/></>;const r=runtime.data;const status=modeStatus(r.mode,r.healthy);const allFailures=failures.data??[];const visibleFailures=showAllFailures?allFailures:allFailures.filter(f=>!f.resolved);return <><SystemTabs/><PageHeader title="시스템 상태"/>
<section className="panel mb-6 p-5"><p className="label">현재 상태</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><p className={`text-2xl font-semibold ${r.healthy?"text-success":"text-warning"}`}>{status.title}</p><p className="mt-1 text-sm text-muted">{status.detail}{r.unresolved_failure_count>0&&` · 미해결 장애 ${r.unresolved_failure_count}건`}</p></div><div className="text-right"><p className="text-xs text-muted">운영 모드</p><StatusBadge value={r.mode} label={formatRuntimeMode(r.mode)}/></div></div></section>
<section className="panel mb-6 overflow-hidden"><div className="border-b border-line px-5 py-4"><h2 className="font-semibold">핵심 구성요소</h2></div><div className="table-wrap border-0"><table><thead><tr><th>항목</th><th>상태</th><th>마지막 확인</th></tr></thead><tbody><ComponentRow name="시세 데이터" value={r.last_market_data} empty="미수신"/><ComponentRow name="주문 실행" value={r.last_execution} empty="미실행"/><ComponentRow name="상태 대조" value={r.last_reconciliation} empty="미실행"/><ComponentRow name="시스템 신호" value={r.last_heartbeat} empty="미수신"/></tbody></table></div></section>
<section className="mb-8"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="font-semibold">{showAllFailures?"전체 장애 기록":`현재 장애 ${r.unresolved_failure_count}건`}</h2><p className="mt-1 text-xs text-muted">해결 처리는 기록만 변경하며 정상 복구와는 별개입니다.</p></div>{allFailures.some(f=>f.resolved)&&<button className="btn-muted px-3 py-2 text-xs" onClick={()=>setShowAllFailures(v=>!v)}>{showAllFailures?"미해결만 보기":"전체 기록 보기"}</button>}</div>{failures.error?<ErrorState message={failures.error} retry={failures.refresh}/>:visibleFailures.length?<div className="table-wrap"><table><thead><tr><th>시각</th><th>유형</th><th>내용</th><th>상태</th><th>작업</th></tr></thead><tbody>{visibleFailures.map(f=><tr key={f.id}><td>{etTime(f.occurred_at)}</td><td><StatusBadge value={f.severity} label={formatSeverity(f.severity)}/></td><td className="max-w-lg"><span>{formatFailureCodeDescription(f.code)}</span><small className="mt-1 block text-muted">{f.message}</small></td><td>{formatResolved(f.resolved)}</td><td>{!f.resolved&&<button className="btn-muted px-2 py-1 text-xs" disabled={busy} onClick={()=>void resolve(f.id)}>해결 처리</button>}</td></tr>)}</tbody></table></div>:<EmptyState title={showAllFailures?"장애 기록이 없습니다.":"현재 미해결 장애가 없습니다."}/>}</section>
<section className="panel mb-6 p-5"><h2 className="font-semibold">시스템 제어</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><Control title="안전 모드" description="신규 진입과 추가매수를 차단하고 기존 포지션의 위험 축소·청산만 허용합니다." buttonClass="btn-muted border-warning text-warning" onClick={()=>setAction("safe-mode")}/><Control title="상태 대조" description="시스템 내부 상태와 Broker 상태가 일치하는지 확인합니다." disabled={busy} onClick={()=>void doReconcile()}/><Control title="정상 복구" description="Backend가 복구 조건을 확인한 뒤 정상 모드로 전환합니다." disabled={busy} onClick={()=>void recover()}/></div><div className="mt-5 border-t border-line pt-5"><Control title="자동 매매 중지" description="자동 Strategy Action을 중단합니다." buttonClass="btn-danger" onClick={()=>setAction("halt")}/></div>{reconcile&&<div className={`mt-4 rounded-lg border p-4 ${reconcile.matched?"border-success bg-success-soft":"border-danger bg-danger-soft"}`}><p className="font-semibold">{reconcile.matched?"PASS":"MISMATCH"}</p>{reconcile.mismatches.map((m,i)=><p key={i} className="mt-2 text-sm text-muted">{m.type} · {m.symbol} · {m.details}</p>)}</div>}</section>
<section className="rounded-xl border border-danger bg-danger-soft p-5"><h2 className="font-semibold text-danger">비상 중지</h2><p className="mt-1 text-sm text-muted">시스템을 중지 상태로 전환하고 Broker 포지션 청산을 시도합니다.</p><button className="btn-danger mt-3" onClick={()=>setAction("kill-switch")}>비상 중지 실행</button></section>
<Modal open={!!action} title={action==="kill-switch"?"비상 중지 (Kill Switch) · 2단계 확인":action==="halt"?"자동 매매 중지":"안전 모드"} onClose={()=>!busy&&setAction(null)}><p className="mb-4 text-sm text-foreground-secondary">{action==="safe-mode"?"신규 진입 및 추가매수를 차단하며 기존 포지션의 위험 축소·청산은 허용됩니다.":action==="halt"?"자동 Strategy Action을 중단합니다.":"시스템을 HALTED 상태로 전환하고 현재 포지션의 청산을 시도할 수 있습니다."}</p><label className="label mb-2 block" htmlFor="reason">운영 사유</label><textarea id="reason" className="input min-h-24" value={reason} onChange={e=>setReason(e.target.value)} placeholder="사유를 입력하세요."/>{action==="kill-switch"&&<label className="mt-4 flex items-start gap-3 rounded-lg border border-danger p-3 text-sm text-danger"><input type="checkbox" className="mt-1" checked={understood} onChange={e=>setUnderstood(e.target.checked)}/><span>현재 포지션 청산 시도가 발생할 수 있음을 이해했습니다.</span></label>}<div className="mt-5 flex justify-end gap-2"><button className="btn-muted" onClick={()=>setAction(null)}>취소</button><button className={action==="safe-mode"?"btn-primary":"btn-danger"} disabled={busy||!reason.trim()||(action==="kill-switch"&&!understood)} onClick={()=>void runAction()}>{action==="kill-switch"?"확인 후 Kill Switch 실행":action==="halt"?"HALTED 전환":"SAFE_MODE 전환"}</button></div></Modal></>}

function ComponentRow({name,value,empty}:{name:string;value:string|null;empty:string}){return <tr><td className="font-medium">{name}</td><td><StatusBadge value={value?"OK":"UNKNOWN"} label={value?"확인됨":"확인 필요"}/></td><td>{recorded(value,empty)}</td></tr>}
function Control({title,description,onClick,buttonClass="btn-muted",disabled=false}:{title:string;description:string;onClick:()=>void;buttonClass?:string;disabled?:boolean}){return <div><button className={buttonClass} disabled={disabled} onClick={onClick}>{title}</button><p className="mt-2 text-xs leading-5 text-muted">{description}</p></div>}
