"use client";
import { api } from "@/lib/api";
import { decimal, etTime } from "@/lib/format";
import { useApi } from "@/hooks/use-api";
import { EmptyState, ErrorState, LoadingState, MetricCard, PageHeader, StatusBadge } from "@/components/ui";
import { formatBrokerMode, formatOrderSide, formatOrderStatus, formatStrategyPhase, formatTradeStatus } from "@/lib/display";

export default function TradingPage(){const overview=useApi(api.trading,10000);const orders=useApi(api.orders,10000);const fills=useApi(api.fills,10000);const trades=useApi(api.trades,10000);if(overview.loading)return <LoadingState/>;if(!overview.data)return <><PageHeader title="매매 현황" description="현재 보유 포지션과 주문, 체결, 매매 결과를 확인합니다."/><ErrorState message={overview.error||"매매 상태 조회 실패"} retry={overview.refresh}/></>;const o=overview.data;return <><PageHeader title="매매 현황" description="현재 보유 포지션과 주문, 체결, 매매 결과를 확인합니다." actions={<StatusBadge value={o.broker_mode} label={formatBrokerMode(o.broker_mode)}/>} />
<section className="mb-6 grid gap-3 sm:grid-cols-3"><MetricCard label="브로커" value={<StatusBadge value={o.broker_mode} label={formatBrokerMode(o.broker_mode)}/>}/><MetricCard label="보유 포지션" value={o.open_positions.length}/><MetricCard label="미체결 주문" value={o.open_orders.length}/></section>
{o.availability==="NO_ACTIVE_SIM_BROKER"&&<div className="mb-6 rounded-xl border border-slate-700 bg-slate-900/60 p-4"><p className="text-sm font-medium text-slate-200">현재 활성화된 Simulation Broker가 없습니다.</p><p className="mt-1 text-xs text-muted">가상 매매가 시작되면 보유 포지션과 주문·체결 내역이 이 화면에 표시됩니다.</p></div>}
<section className="mb-7"><h2 className="mb-3 font-semibold">보유 포지션 및 전략 상태</h2>{o.strategy_states.length?<div className="grid gap-4 lg:grid-cols-2">{o.strategy_states.map((p,i)=><div className="panel p-5" key={`${p.symbol}-${p.variant}-${i}`}><div className="mb-4 flex items-center justify-between"><span className="text-xl font-bold">{p.symbol}</span><StatusBadge value={p.phase} label={formatStrategyPhase(p.phase)} showRaw/></div><p className="label mb-2">포지션 정보</p><div className="rounded-lg border border-line bg-slate-950/40 p-3 text-sm text-muted">수량·현재가·PnL은 현재 API 응답에 기록된 값이 없습니다.</div><p className="label mb-2 mt-4">전략 상태</p><dl className="grid grid-cols-2 gap-x-5 gap-y-3 text-sm sm:grid-cols-4">{[["Phase",formatStrategyPhase(p.phase)],["Initial Stop",decimal(p.initial_stop)],["Active Stop",decimal(p.active_stop)],["Highest",decimal(p.highest_price)],["Add Count",p.add_count],["Holding Day",p.holding_day],["Overnight",p.overnight?"YES":"NO"],["전략",`${p.book} · ${p.variant}`]].map(([k,v])=><div key={k}><dt className="text-xs text-muted">{k}</dt><dd className="mt-1 text-slate-200">{v}</dd></div>)}</dl></div>)}</div>:<EmptyState title="현재 보유 포지션이 없습니다." description="가상 매매가 시작되면 포지션과 전략 상태가 표시됩니다."/>}</section>
<section className="mb-7"><h2 className="mb-3 font-semibold">주문 내역</h2>{orders.data?.length?<div className="table-wrap"><table><thead><tr><th>시각</th><th>종목</th><th>방향</th><th>주문 수량</th><th>체결 수량</th><th>기준가</th><th>상태</th></tr></thead><tbody>{orders.data.map(x=><tr key={x.order_id}><td>{etTime(x.submitted_at)}</td><td className="font-bold text-white">{x.symbol}</td><td>{formatOrderSide(x.side)}</td><td>{decimal(x.requested_quantity)}</td><td>{decimal(x.filled_quantity)}</td><td>{decimal(x.reference_price)}</td><td><StatusBadge value={x.status} label={formatOrderStatus(x.status)}/></td></tr>)}</tbody></table></div>:<EmptyState title="주문 내역이 없습니다."/>}</section>
<section className="mb-7"><h2 className="mb-3 font-semibold">체결 내역</h2>{fills.data?.length?<div className="table-wrap"><table><thead><tr><th>시각</th><th>종목</th><th>수량</th><th>체결가</th><th>Spread</th><th>Slippage</th><th>수수료</th><th>총비용</th></tr></thead><tbody>{fills.data.map(x=><tr key={x.fill_id}><td>{etTime(x.filled_at)}</td><td>{x.symbol}</td><td>{decimal(x.quantity)}</td><td>{decimal(x.fill_price)}</td><td>{decimal(x.spread_cost)}</td><td>{decimal(x.slippage_cost)}</td><td>{decimal(x.commission)}</td><td>{decimal(x.total_cost)}</td></tr>)}</tbody></table></div>:<EmptyState title="체결 내역이 없습니다."/>}</section>
<section><h2 className="mb-3 font-semibold">최근 매매 결과</h2>{trades.data?.length?<div className="table-wrap"><table><thead><tr><th>종목</th><th>전략</th><th>상태</th><th>진입</th><th>청산</th><th>Gross PnL</th><th>Net PnL</th><th>Gross R</th><th>Net R</th><th>청산 사유</th></tr></thead><tbody>{trades.data.map(x=><tr key={x.id}><td className="font-bold">{x.symbol}</td><td>{x.variant}</td><td><StatusBadge value={x.status} label={formatTradeStatus(x.status)}/></td><td>{decimal(x.entry)}</td><td>{decimal(x.exit)}</td><td>{decimal(x.gross_pnl)}</td><td className={x.net_pnl.startsWith("-")?"text-red-300":"text-emerald-300"}>{x.net_pnl.startsWith("-")?"":"+"}{decimal(x.net_pnl)}</td><td>{decimal(x.gross_r,"R")}</td><td>{decimal(x.net_r,"R")}</td><td>{x.exit_reason||"기록 없음"}</td></tr>)}</tbody></table></div>:<EmptyState title="완료된 매매가 없습니다."/>}</section></>}
